.\"
.\" Copyright (C) 2018 Red Hat, Inc. All Rights Reserved.
.\" Written by David Howells (dhowells@redhat.com)
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version
.\" 2 of the License, or (at your option) any later version.
.\"
.TH AKLOG-KAFS 1 "16 Apr 2019" Linux "AFS Kerberos authentication"
.SH NAME
aklog-kafs \- AFS Kerberos authentication tool
.SH SYNOPSIS
\fBaklog-kafs\fR [<cell> [<realm>]]
.P
.B
*** NOTE THE ABOVE IS PROVISIONAL AND IS LIKELY TO CHANGE ***
.R
.SH DESCRIPTION
This program is used to get an authentication ticket from Kerberos that can be
used by the in-kernel AFS filesystem (kAFS) to perform authenticated and
encrypted accesses to the server.  Without this only unencrypted anonymous
accesses can be made.
.P
Before calling this, the \fBkinit\fR program or similar should be invoked to
authenticate with the appropriate Kerberos server.
.SH ARGUMENTS
.IP <cell>
This is the name of the cell with which the ticket is intended to be used.  If
not given, the name of the default cell will be read from
\fB/proc/net/afs/rootcell\fR and used instead.
.IP <realm>
This is the name of the Kerberos realm from which the ticket will be obtained.
.SH ERRORS
.SH SEE ALSO
.ad l
.nh
.BR kinit (1)
